package com.usaparel.model.VO.REBATE;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 11 08:59:02 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VOSummary2RowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        NoOfCases,
        Status,
        TotalRebateAmount,
        TotalEsitmate,
        TotalReceived;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int NOOFCASES = AttributesEnum.NoOfCases.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int TOTALREBATEAMOUNT = AttributesEnum.TotalRebateAmount.index();
    public static final int TOTALESITMATE = AttributesEnum.TotalEsitmate.index();
    public static final int TOTALRECEIVED = AttributesEnum.TotalReceived.index();

    /**
     * This is the default constructor (do not remove).
     */
    public VOSummary2RowImpl() {
    }
}

