package com.usaparel.model.VO.REBATE;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 11 08:59:03 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VOSummary2Impl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public VOSummary2Impl() {
    }
}

